// Code generated by MockGen. DO NOT EDIT.
// Source: patreon/internal/app/delivery/http/handler_factory (interfaces: UsecaseFactory)

// Package mock_usecase_factory is a generated GoMock package.
package mock_usecase_factory

import (
	usecase_csrf "patreon/internal/app/csrf/usecase"
	sessions "patreon/internal/app/sessions"
	usecase_awards "patreon/internal/app/usecase/awards"
	usecase_creator "patreon/internal/app/usecase/creator"
	usecase_likes "patreon/internal/app/usecase/likes"
	payments "patreon/internal/app/usecase/payments"
	posts "patreon/internal/app/usecase/posts"
	posts_data "patreon/internal/app/usecase/posts_data"
	usecase_subscribers "patreon/internal/app/usecase/subscribers"
	usercase_user "patreon/internal/app/usecase/user"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUsecaseFactory is a mock of UsecaseFactory interface.
type MockUsecaseFactory struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseFactoryMockRecorder
}

// MockUsecaseFactoryMockRecorder is the mock recorder for MockUsecaseFactory.
type MockUsecaseFactoryMockRecorder struct {
	mock *MockUsecaseFactory
}

// NewMockUsecaseFactory creates a new mock instance.
func NewMockUsecaseFactory(ctrl *gomock.Controller) *MockUsecaseFactory {
	mock := &MockUsecaseFactory{ctrl: ctrl}
	mock.recorder = &MockUsecaseFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecaseFactory) EXPECT() *MockUsecaseFactoryMockRecorder {
	return m.recorder
}

// GetAwardsUsecase mocks base method.
func (m *MockUsecaseFactory) GetAwardsUsecase() usecase_awards.Usecase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAwardsUsecase")
	ret0, _ := ret[0].(usecase_awards.Usecase)
	return ret0
}

// GetAwardsUsecase indicates an expected call of GetAwardsUsecase.
func (mr *MockUsecaseFactoryMockRecorder) GetAwardsUsecase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAwardsUsecase", reflect.TypeOf((*MockUsecaseFactory)(nil).GetAwardsUsecase))
}

// GetCreatorUsecase mocks base method.
func (m *MockUsecaseFactory) GetCreatorUsecase() usecase_creator.Usecase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCreatorUsecase")
	ret0, _ := ret[0].(usecase_creator.Usecase)
	return ret0
}

// GetCreatorUsecase indicates an expected call of GetCreatorUsecase.
func (mr *MockUsecaseFactoryMockRecorder) GetCreatorUsecase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCreatorUsecase", reflect.TypeOf((*MockUsecaseFactory)(nil).GetCreatorUsecase))
}

// GetCsrfUsecase mocks base method.
func (m *MockUsecaseFactory) GetCsrfUsecase() usecase_csrf.Usecase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCsrfUsecase")
	ret0, _ := ret[0].(usecase_csrf.Usecase)
	return ret0
}

// GetCsrfUsecase indicates an expected call of GetCsrfUsecase.
func (mr *MockUsecaseFactoryMockRecorder) GetCsrfUsecase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCsrfUsecase", reflect.TypeOf((*MockUsecaseFactory)(nil).GetCsrfUsecase))
}

// GetLikesUsecase mocks base method.
func (m *MockUsecaseFactory) GetLikesUsecase() usecase_likes.Usecase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLikesUsecase")
	ret0, _ := ret[0].(usecase_likes.Usecase)
	return ret0
}

// GetLikesUsecase indicates an expected call of GetLikesUsecase.
func (mr *MockUsecaseFactoryMockRecorder) GetLikesUsecase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLikesUsecase", reflect.TypeOf((*MockUsecaseFactory)(nil).GetLikesUsecase))
}

// GetPaymentsUsecase mocks base method.
func (m *MockUsecaseFactory) GetPaymentsUsecase() payments.Usecase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentsUsecase")
	ret0, _ := ret[0].(payments.Usecase)
	return ret0
}

// GetPaymentsUsecase indicates an expected call of GetPaymentsUsecase.
func (mr *MockUsecaseFactoryMockRecorder) GetPaymentsUsecase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentsUsecase", reflect.TypeOf((*MockUsecaseFactory)(nil).GetPaymentsUsecase))
}

// GetPostsDataUsecase mocks base method.
func (m *MockUsecaseFactory) GetPostsDataUsecase() posts_data.Usecase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostsDataUsecase")
	ret0, _ := ret[0].(posts_data.Usecase)
	return ret0
}

// GetPostsDataUsecase indicates an expected call of GetPostsDataUsecase.
func (mr *MockUsecaseFactoryMockRecorder) GetPostsDataUsecase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostsDataUsecase", reflect.TypeOf((*MockUsecaseFactory)(nil).GetPostsDataUsecase))
}

// GetPostsUsecase mocks base method.
func (m *MockUsecaseFactory) GetPostsUsecase() posts.Usecase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostsUsecase")
	ret0, _ := ret[0].(posts.Usecase)
	return ret0
}

// GetPostsUsecase indicates an expected call of GetPostsUsecase.
func (mr *MockUsecaseFactoryMockRecorder) GetPostsUsecase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostsUsecase", reflect.TypeOf((*MockUsecaseFactory)(nil).GetPostsUsecase))
}

// GetSessionManager mocks base method.
func (m *MockUsecaseFactory) GetSessionManager() sessions.SessionsManager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionManager")
	ret0, _ := ret[0].(sessions.SessionsManager)
	return ret0
}

// GetSessionManager indicates an expected call of GetSessionManager.
func (mr *MockUsecaseFactoryMockRecorder) GetSessionManager() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionManager", reflect.TypeOf((*MockUsecaseFactory)(nil).GetSessionManager))
}

// GetSubscribersUsecase mocks base method.
func (m *MockUsecaseFactory) GetSubscribersUsecase() usecase_subscribers.Usecase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscribersUsecase")
	ret0, _ := ret[0].(usecase_subscribers.Usecase)
	return ret0
}

// GetSubscribersUsecase indicates an expected call of GetSubscribersUsecase.
func (mr *MockUsecaseFactoryMockRecorder) GetSubscribersUsecase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscribersUsecase", reflect.TypeOf((*MockUsecaseFactory)(nil).GetSubscribersUsecase))
}

// GetUserUsecase mocks base method.
func (m *MockUsecaseFactory) GetUserUsecase() usercase_user.Usecase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserUsecase")
	ret0, _ := ret[0].(usercase_user.Usecase)
	return ret0
}

// GetUserUsecase indicates an expected call of GetUserUsecase.
func (mr *MockUsecaseFactoryMockRecorder) GetUserUsecase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserUsecase", reflect.TypeOf((*MockUsecaseFactory)(nil).GetUserUsecase))
}
