// Code generated by MockGen. DO NOT EDIT.
// Source: patreon/internal/app/repository/posts_data (interfaces: Repository)

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	models "patreon/internal/app/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// PostsDataRepository is a mock of Repository interface.
type PostsDataRepository struct {
	ctrl     *gomock.Controller
	recorder *PostsDataRepositoryMockRecorder
}

// PostsDataRepositoryMockRecorder is the mock recorder for PostsDataRepository.
type PostsDataRepositoryMockRecorder struct {
	mock *PostsDataRepository
}

// NewPostsDataRepository creates a new mock instance.
func NewPostsDataRepository(ctrl *gomock.Controller) *PostsDataRepository {
	mock := &PostsDataRepository{ctrl: ctrl}
	mock.recorder = &PostsDataRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *PostsDataRepository) EXPECT() *PostsDataRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *PostsDataRepository) Create(arg0 *models.PostData) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *PostsDataRepositoryMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*PostsDataRepository)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *PostsDataRepository) Delete(arg0 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *PostsDataRepositoryMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*PostsDataRepository)(nil).Delete), arg0)
}

// ExistsData mocks base method.
func (m *PostsDataRepository) ExistsData(arg0 int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsData", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsData indicates an expected call of ExistsData.
func (mr *PostsDataRepositoryMockRecorder) ExistsData(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsData", reflect.TypeOf((*PostsDataRepository)(nil).ExistsData), arg0)
}

// Get mocks base method.
func (m *PostsDataRepository) Get(arg0 int64) (*models.PostData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(*models.PostData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *PostsDataRepositoryMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*PostsDataRepository)(nil).Get), arg0)
}

// GetData mocks base method.
func (m *PostsDataRepository) GetData(arg0 int64) ([]models.PostData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetData", arg0)
	ret0, _ := ret[0].([]models.PostData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetData indicates an expected call of GetData.
func (mr *PostsDataRepositoryMockRecorder) GetData(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetData", reflect.TypeOf((*PostsDataRepository)(nil).GetData), arg0)
}

// Update mocks base method.
func (m *PostsDataRepository) Update(arg0 *models.PostData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *PostsDataRepositoryMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*PostsDataRepository)(nil).Update), arg0)
}
