// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models_utilits

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonBa3ae9faDecodePatreonInternalAppUtilitsModels(in *jlexer.Lexer, out *MapOfUnmarshalError) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
	} else {
		in.Delim('{')
		*out = make(MapOfUnmarshalError)
		for !in.IsDelim('}') {
			key := string(in.String())
			in.WantColon()
			var v1 string
			v1 = string(in.String())
			(*out)[key] = v1
			in.WantComma()
		}
		in.Delim('}')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBa3ae9faEncodePatreonInternalAppUtilitsModels(out *jwriter.Writer, in MapOfUnmarshalError) {
	if in == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
		out.RawString(`null`)
	} else {
		out.RawByte('{')
		v2First := true
		for v2Name, v2Value := range in {
			if v2First {
				v2First = false
			} else {
				out.RawByte(',')
			}
			out.String(string(v2Name))
			out.RawByte(':')
			out.String(string(v2Value))
		}
		out.RawByte('}')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v MapOfUnmarshalError) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBa3ae9faEncodePatreonInternalAppUtilitsModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MapOfUnmarshalError) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBa3ae9faEncodePatreonInternalAppUtilitsModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MapOfUnmarshalError) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBa3ae9faDecodePatreonInternalAppUtilitsModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MapOfUnmarshalError) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBa3ae9faDecodePatreonInternalAppUtilitsModels(l, v)
}
