// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package push_server

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson316682a0DecodePatreonInternalMicroservicesPushDeliveryServer(in *jlexer.Lexer, out *PushResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "type":
			out.Type = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson316682a0EncodePatreonInternalMicroservicesPushDeliveryServer(out *jwriter.Writer, in PushResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PushResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson316682a0EncodePatreonInternalMicroservicesPushDeliveryServer(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PushResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson316682a0EncodePatreonInternalMicroservicesPushDeliveryServer(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PushResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson316682a0DecodePatreonInternalMicroservicesPushDeliveryServer(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PushResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson316682a0DecodePatreonInternalMicroservicesPushDeliveryServer(l, v)
}
