// Code generated by MockGen. DO NOT EDIT.
// Source: patreon/internal/app/repository/payments (interfaces: Repository)

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	models "patreon/internal/app/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// PaymentsRepository is a mock of Repository interface.
type PaymentsRepository struct {
	ctrl     *gomock.Controller
	recorder *PaymentsRepositoryMockRecorder
}

// PaymentsRepositoryMockRecorder is the mock recorder for PaymentsRepository.
type PaymentsRepositoryMockRecorder struct {
	mock *PaymentsRepository
}

// NewPaymentsRepository creates a new mock instance.
func NewPaymentsRepository(ctrl *gomock.Controller) *PaymentsRepository {
	mock := &PaymentsRepository{ctrl: ctrl}
	mock.recorder = &PaymentsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *PaymentsRepository) EXPECT() *PaymentsRepositoryMockRecorder {
	return m.recorder
}

// GetCreatorPayments mocks base method.
func (m *PaymentsRepository) GetCreatorPayments(arg0 int64) ([]models.Payments, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCreatorPayments", arg0)
	ret0, _ := ret[0].([]models.Payments)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCreatorPayments indicates an expected call of GetCreatorPayments.
func (mr *PaymentsRepositoryMockRecorder) GetCreatorPayments(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCreatorPayments", reflect.TypeOf((*PaymentsRepository)(nil).GetCreatorPayments), arg0)
}

// GetUserPayments mocks base method.
func (m *PaymentsRepository) GetUserPayments(arg0 int64) ([]models.Payments, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPayments", arg0)
	ret0, _ := ret[0].([]models.Payments)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPayments indicates an expected call of GetUserPayments.
func (mr *PaymentsRepositoryMockRecorder) GetUserPayments(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPayments", reflect.TypeOf((*PaymentsRepository)(nil).GetUserPayments), arg0)
}
